/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheRecordRouteImport } from './routes/the-record'
import { Route as IndexRouteImport } from './routes/index'

const TheRecordRoute = TheRecordRouteImport.update({
  id: '/the-record',
  path: '/the-record',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/the-record': typeof TheRecordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/the-record': typeof TheRecordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/the-record': typeof TheRecordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/the-record'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/the-record'
  id: '__root__' | '/' | '/the-record'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TheRecordRoute: typeof TheRecordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-record': {
      id: '/the-record'
      path: '/the-record'
      fullPath: '/the-record'
      preLoaderRoute: typeof TheRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TheRecordRoute: TheRecordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
